### ISSUE TITLE
求0.8的deb包，flatpak也行

### ISSUE THREAD

**Issue by Error-1x** [rekols/redict#11]
大神，编译安装好不方便啊，求一个能直接安装的deb包或者flatpak包
谢谢大神。

**Comment by rekols** [comment]
https://github.com/rekols/redict/releases/tag/0.8

**Comment by rekols** [comment]
刚打了一个 deb，外网的 dtk 可用。

**Comment by Error-1x** [comment]
大神，我刚看到你打包的消息，早知道我就不打Appimage包了。一会我发到bbs，让所有发行版都可以运行你的软件
https://pan.baidu.com/s/1_p0HA-iuFb-POlv0LbCrWA

**Comment by rekols** [comment]
可以的

**Comment by rekols** [comment]
appimage 我不会打，哈哈哈。

**Comment by rekols** [comment]
@Error-1x 你应该发一个新帖子。:)

**Comment by Error-1x** [comment]
没问题，谢谢大神写这么实用的软件

**Comment by rekols** [comment]
:)
