### ISSUE TITLE
从仓库clone最新的代码重新编译后不能屏幕取词了

### ISSUE THREAD

**Issue by zhiw2019** [rekols/redict#12]
RT

**Comment by rekols** [comment]
是划线取词还是屏幕取词？

**Comment by rekols** [comment]
@zhiw2019 这个是redict-dtk里面有的

**Comment by zhiw2019** [comment]
哦，仓库改名了？那redict-dtk和redict两个项目啥关系？区别？

**Comment by rekols** [comment]
@zhiw2019 一个是用 dtk，就是专门在deepin下运行的，一个redict是纯qt的，可以在任何发行版运行，redict-dtk相等于deepin专版。

**Comment by zhiw2019** [comment]
哦，明白了。那后续纯qt的redict支持划线取词么？

**Comment by rekols** [comment]
支持吧
