### ISSUE TITLE
命令行下qmake不了，但可以用qt编译成功

### ISSUE THREAD

**Issue by lcx10086** [rekols/redict#4]
![image](https://user-images.githubusercontent.com/26214474/42919504-df9d23e6-8b44-11e8-917b-8d5c9e8e3d01.png)
![image](https://user-images.githubusercontent.com/26214474/42919511-e89765ba-8b44-11e8-9693-fd23bfbddb29.png)

**Comment by rekols** [comment]
sudo apt install g++ qt5-default

**Comment by lcx10086** [comment]
已经安装过了，系统环境是ubuntu
![image](https://user-images.githubusercontent.com/26214474/42920559-ea406420-8b49-11e8-9dbd-872279f72a7c.png)

**Comment by rekols** [comment]
看看qt5-qmake这个包。

**Comment by lcx10086** [comment]
![image](https://user-images.githubusercontent.com/26214474/42920771-0323139c-8b4b-11e8-8110-455426839ad2.png)

**Comment by lcx10086** [comment]
已经找到原因了，是因为我把自己下的qt的qmake放在了终端目录下面，移除就能使用系统的qmake编译成功
![image](https://user-images.githubusercontent.com/26214474/42922371-e0dd658c-8b52-11e8-9544-cd509005f2ed.png)

**Comment by lcx10086** [comment]
运行的时候会提示
![image](https://user-images.githubusercontent.com/26214474/42923616-f1358684-8b58-11e8-8b03-e86ff2189ac2.png)

**Comment by rekols** [comment]
上面的的提示是没有错误的。
